export enum Campos {
    disciplinas = 'disciplinas',
    areaConhecimento = 'AreaConhecimento',
    matriz = 'matriz',
    competencia = 'competencia',
    habilidade = 'habilidade',
    anoMatriz = 'anoMatriz',
    dificuldadeSugerida = 'dificuldadeSugerida',
    assunto = 'assunto',
    subAssunto = 'subAssunto',
    situacaoItem = 'situacaoItem',
    tipoItem = 'tipoItem',
    quantidadeAlternativas = 'quantidadeAlternativas',
    discriminacao = 'infoEstatisticasDiscriminacao',
    dificuldade = 'infoEstatisticasDificuldade',
    acertoCasual = 'infoEstatisticasAcertoCasual',
    palavraChave = 'palavraChave',
    parametroBTransformado = 'parametroBTransformado',
    mediaDesvioPadrao = 'mediaDesvioPadrao',
    observacao = 'observacao',
    nivelItem = 'nivelItem',
    sentencaDescritora = 'sentencaDescritora',
    
    // ✅ Novos campos para FormularioElaboracaoComponent
    textoBase = 'textoBase',
    fonte = 'fonte',
    enunciado = 'enunciado',
    codigoItem = 'codigoItem',
    video = 'video',
    audio = 'audio',
    alternativaA = 'alternativaA',
    justificativaA = 'justificativaA',
    alternativaB = 'alternativaB',
    justificativaB = 'justificativaB',
    alternativaC = 'alternativaC',
    justificativaC = 'justificativaC',
    alternativaD = 'alternativaD',
    justificativaD = 'justificativaD',
    alternativaCorreta = 'alternativaCorreta',
}

export enum DadosIniciais {
    tipoItemIdPadrao = 1,
}
