export enum Campos {
    disciplinas = 'disciplinas',
    areaConhecimento = 'AreaConhecimento',
    matriz = 'matriz',
    competencia = 'competencia',
    habilidade = 'habilidade',
    anoMatriz = 'anoMatriz',
    dificuldadeSugerida = 'dificuldadeSugerida',
    assunto = 'assunto',
    subAssunto = 'subAssunto',
    situacaoItem = 'situacaoItem',
    tipoItem = 'tipoItem',
    quantidadeAlternativas = 'quantidadeAlternativas',
    discriminacao = 'infoEstatisticasDiscriminacao',
    dificuldade = 'infoEstatisticasDificuldade',
    acertoCasual = 'infoEstatisticasAcertoCasual',
    palavraChave = 'palavraChave',
    parametroBTransformado = 'parametroBTransformado',
    mediaDesvioPadrao = 'mediaDesvioPadrao',
    observacao = 'observacao',
}
